version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  assignees:
  - yosiat
  - shamil
  - ramhr
